sorry, massive changes for a first pr :(
ncskth/bifrost pull request #4
Opened 2021-09-10 23:38 UTC by chanokin

2021-09-14 10:05 UTC, Jegp requested changes
Thank you so much for the massive amount of work you put here Gary!

In general, I think this is excellent! I have one thing I'd like to understand before going ahead and a few minor comments that are not essential for now, I think.

* The `export_cell_params` in `export/population.py` is a little hard for me to understand. Can we in any way wrap that in the context class? It could also make sense to retain here. I may just not be understanding it.
* Of minor comments, I have a slightly hard time reading some of your variable names. I would prefer `layer_parameters` instead of `lparams`, for instance.
* I also appreciate your emphasis on spacing in the final output, but I was never under the impression that the output code should be humanly readable. Should that change? Would it make sense to generate "pretty" code?
* Finally, I think we should have some more tests. I realize I'm also to blame, but I would maybe suggest we get some coverage statistics soon, just so we can know how good/bad we are :-)

Thanks again for the effort Gary!

2021-09-14 10:40 UTC, chanokin commented on bifrost/export/input.py
> +def export_poisson_image_dataset_input(layer: InputLayer, ctx: ParameterContext[str]) -> Statement:
this is still not implemented 😝

2021-09-14 10:42 UTC, chanokin commented on bifrost/export/population.py
> +    # todo: take 'locations/addresses' from context and express as a function
This is still context dependent, it obtains the value from the external file. We can move it to the context side but I'm not sure it really makes a difference and at least here, it's in the 'export package'

2021-09-14 10:44 UTC, chanokin commented on bifrost/export/torch.py
> +def try_reduce_param(param):
😢 this is not a Python problem, it's the delightful joys of using sPyNNaker. Instead of dealing with these cases, they just throw an Exception

2021-09-14 10:46 UTC, chanokin commented on bifrost/ir/connection.py
>  class AllToAllConnector(Connector):
Not sure yet, this could be used to separate from the standard All-to-All and the Pooling+Dense connectors

2021-09-14 10:46 UTC, chanokin commented on bifrost/ir/input.py
> +    # : Dict[int, str]  # keys are order, thus ints
agreed

2021-09-14 10:46 UTC, chanokin commented on bifrost/ir/input.py
> +class DummyTestInputSource(InputSource):
If this is not part of the package I expect an error from source parsing

2021-09-14 10:47 UTC, chanokin commented on bifrost/ir/output.py
> +class DummyTestOutputSink(OutputSink):
Just like the one before, If this is not part of the package I expect an error

2021-09-14 10:52 UTC, chanokin commented
>     * The `export_cell_params` in `export/population.py` is a little hard for me to understand. Can we in any way wrap that in the context class? It could also make sense to retain here. I may just not be understanding it.

 
>     * Of minor comments, I have a slightly hard time reading some of your variable names. I would prefer `layer_parameters` instead of `lparams`, for instance.

Yup, I'll do a pass to rename weird shit
 
>     * I also appreciate your emphasis on spacing in the final output, but I was never under the impression that the output code should be humanly readable. Should that change? Would it make sense to generate "pretty" code?

My issue with this is that *if* we need to inspect the code to figure stuff out, the file is super annoying to read. 

As for 'compacting' the variables into dictionaries, when I open the files in an IDE, my computer turns into a turtle due to syntax inspection. Plus, I _think_ it's less prone to errors.

>     * Finally, I think we should have some more tests. I realize I'm also to blame, but I would maybe suggest we get some coverage statistics soon, just so we can know how good/bad we are :-)

Agreed, I'll start on more tests now that I've managed to run a 'full' script.

2021-09-14 18:27 UTC, Jegp commented on bifrost/export/population.py
> +    # todo: take 'locations/addresses' from context and express as a function
Hmmm ok. After a second look, it actually does make sense. I guess this is what you get when you want to have parameterized code generation.

2021-09-14 18:27 UTC, Jegp commented on bifrost/export/torch.py
> +def try_reduce_param(param):
Thanks Obama!

2021-09-14 18:32 UTC, Jegp commented on bifrost/ir/connection.py
>  class AllToAllConnector(Connector):
I see the need to distinguish All-to-All and Pooling connectors, but for me a "Dense" connector is similar to a MatrixConnector. Would it make sense to rename the `DenseConnector` to `PoolingConnector` then? It makes slightly more sense to me.

2021-09-14 18:35 UTC, Jegp commented
Cool. I'm buying your arguments on spacing, and I think we agree on the naming stuff. If you'd like to, please to ahead with the smaller changes. Otherwise, I'd suggest we go ahead and merge it. Would you prefer that I do the merge? :)

2021-09-15 08:00 UTC, chanokin commented
I'll merge after adding some more tests

2021-09-15 10:38 UTC, merged